import Sidebar from "@/components/layout/sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function SuperiaLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className="flex">
        <Sidebar />
        <main className="flex-1">
            {children}
        </main>
    </div>
  );
}
